[application]
name = "submora"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"
sub_package = "submora-web"

[web.app]
title = "Submora"

[web.watcher]
reload_html = true
watch_path = ["frontend/src", "assets", "packages/shared/src", "packages/core/src"]
